# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a9ba1218a234fac443eff370cf90ad1cbea3e5040d3deb760bf86ef9f33cec94284f57e29de8bc2498df7f3489b397c70d5a12171156083e76c7746b08efaf

test:
  secret_key_base: 74bfeb54fcdd3a042ee55b4c0ef6dfbd6346aae0d5fac6422f231a35ec2dd83edd9d085c3aa86f7e75daf9695c44584d716171d9ae453e4f57c3c8dcf52d9678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
